name: Build JavaScript lib

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deployment:
    strategy:
      fail-fast: false
      matrix:
        os:
          # - macos-latest
          - ubuntu-latest
          # - windows-latest
        ocaml-compiler:
          - 4.14.1

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # OCaml build
      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
      - name: Install OCaml dependencies
        run: |
          opam install dune ppx_deriving num.1.4
          opam install js_of_ocaml-compiler js_of_ocaml-ppx
      # - run: |
      #     cd src
      #     opam install . --deps-only
      - name: Build
        run: |
          opam exec -- dune build --profile release Main/ace_js.bc.js
          cp _build/default/Main/ace_js.bc.js html/ace_js.bc.js
          opam exec -- dune build --profile release Main/seed_tools_js.bc.js
          cp _build/default/Main/seed_tools_js.bc.js html/scripts/seed/seed_tools_js.bc.js
     
      - name: Zip offline version
        run: |
          cd html
          zip -r ../app.zip ./*
          mv ../app.zip ./app.zip

      # Upload artifact
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: html/
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
